### ISSUE TITLE
I have a png decoded from base64 into a string

### ISSUE THREAD

**Issue by jorjun** [SolitudeSF/imageman#6]
In my web server I download a png from a httpclient which is in base64, which I decode into a string.

Can I use imageman to resize this png (in string form) without writing to a file, so I can return the resized image in my HTTP response? 

Could I get the array of resulting pixel values to help me convert the result to a BMP?

**Comment by SolitudeSF** [comment]
you can use `readImage` and `writePNG` to open/write images in memory. Sadly, in my rewrite to support multiple image decoding/encoding backends these functions became much less discoverable
`data` field of an image contains sequence with pixel data.
