### ISSUE TITLE
`from imageman import nil` gives undeclared errors

### ISSUE THREAD

**Issue by Wh1teDuke** [SolitudeSF/imageman#8]
**Test**
```nim
from imageman import nil
let img = imageman.loadImage[imageman.ColorRGBU]("sample.png") # Taken from `flip.nim`
```
**Error**
```nim
imageman-master/src/imageman/private/libjpeg.nim(299, 36) Error: undeclared field: 'colorType' 
```

**Comment by SolitudeSF** [comment]
fixed in https://github.com/SolitudeSF/imageman/commit/e91e159008ed528006be4eb844edcb23f15eb9ee
but this is some bizarre nim issue, so you'll probably hit some more if you continue using `import nil`.

**Comment by SolitudeSF** [comment]
i think pretty much every method called template is going to break, but im not going to sacrifice ergonomics for that, so this should be fixed in nim.

**Comment by Wh1teDuke** [comment]
> fixed in [e91e159](https://github.com/SolitudeSF/imageman/commit/e91e159008ed528006be4eb844edcb23f15eb9ee)
> but this is some bizarre nim issue, so you'll probably hit some more if you continue using `import nil`.

Thank you.



> i think pretty much every method called template is going to break, but im not going to sacrifice ergonomics for that, so this should be fixed in nim.

A shame you seemed an honest man.

**Comment by SolitudeSF** [comment]
im not sure now which templates break, so if you encounter same error, you can ping me, maybe it can be a harmless patch.

**Comment by Wh1teDuke** [comment]
Talking of which, are you thinking on adding more complex features like https://github.com/treeform/pixie ? I prefer libraries with few or zero dependencies.

**Comment by SolitudeSF** [comment]
this is a hobby project, so idk. im not sure its realistic for me to keep up with pixie. what features are you looking for?

**Comment by Wh1teDuke** [comment]
> what features are you looking for?

![Screenshot_2021-03-23 treeform pixie](https://user-images.githubusercontent.com/5203140/112160553-90084000-8bea-11eb-8578-7c34a6dc4873.png)

**Comment by SolitudeSF** [comment]
i would advise to switch to pixie then
